spring:
  datasource:
    url: ENC(DCkUgF15KmME4YCmODj99oxs8XQbOmPgpM3LFEY0ov9xOGaF6OoGWSOOjrbzz25Ihrzj0OuYPxjqFU0vqrRfd8f//N/daMuxdTWr9ZRK3pAWjLsEg+0kYQ==)
    username: ENC(kRCjAEUw2S+i3qTBPbYlmWCqUUfGUEMs)
    password: ENC(SBpPWXRL9rPFsgq3rud6P2eKIcV+kan4)
    driver-class-name: org.mariadb.jdbc.Driver

jasypt:
  encryptor:
    bean: jasyptStringEncryptor